# Generated by Django 3.0.11 on 2021-02-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0175_orderrefund_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("asset_id", models.CharField(max_length=200)),
                ("subscribertype_id", models.CharField(max_length=200)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cinesend_product",
                        to="pretixbase.Item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CineSendVoucher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=200)),
                ("url", models.URLField(null=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cinesend_vouchers",
                        to="pretixbase.OrderPosition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CineSendPass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("subscriber_id", models.CharField(max_length=200)),
                ("invite_url", models.URLField(null=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cinesend_passes",
                        to="pretixbase.OrderPosition",
                    ),
                ),
            ],
        ),
    ]
